# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eval_marker_cpp <- function(B, m) {
    .Call(`_SimSurvNMarker_eval_marker`, B, m)
}

#' @export
get_gl_rule <- function(n) {
    .Call(`_SimSurvNMarker_get_gl_rule`, n)
}

glq <- function(lb, ub, nodes, weights, f) {
    .Call(`_SimSurvNMarker_glq`, lb, ub, nodes, weights, f)
}

get_ns_ptr <- function(knots, boundary_knots, intercept) {
    .Call(`_SimSurvNMarker_get_ns_ptr`, knots, boundary_knots, intercept)
}

ns_cpp <- function(x, ns_ptr) {
    .Call(`_SimSurvNMarker_ns_cpp`, x, ns_ptr)
}

